#!/bin/sh
set -e
glib-compile-schemas /usr/share/glib-2.0/schemas
gtk-update-icon-cache /usr/share/icons/hicolor /usr/share/icons/Adwaita /usr/share/icons/ubuntu-mono-dark /usr/share/icons/ubuntu-mono-light
